name: Feature Test
on:
    push:
        branches:
            - feature/**
            # Uncomment the line below to build commits on main
            # This is commented out by default to minimize scratch org usage
            #- main
jobs:
    feature-test:
        name: "Feature Test"
        uses: muselab-d2x/d2x/.github/workflows/feature-test.yml@main
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.GH_EMAIL }}"
            github-token: "${{ secrets.GITHUB_TOKEN }}"